project:
  type: website

website:
  title: "Exposure Triangle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demo.qmd
        text: Presentation Demo
      # - href: static.html
        # text: Static page

format:
  html:
    theme:
      - wj.scss
      - brand
    toc: true



